<template><h1 id="installation" tabindex="-1"><a class="header-anchor" href="#installation" aria-hidden="true">#</a> Installation</h1>
<div class="language-bash ext-sh line-numbers-mode"><pre v-pre class="language-bash"><code><span class="token function">npm</span> <span class="token function">install</span> @lawandorga/components
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br></div></div><h2 id="setup" tabindex="-1"><a class="header-anchor" href="#setup" aria-hidden="true">#</a> Setup</h2>
<p>Setup Tailwind CSS according to their <a href="https://tailwindcss.com/docs/installation" target="_blank" rel="noopener noreferrer">docs</a> and use the following config. You need to change the content settings according to your project. But leave <code>node_modules/@lawandorga/components/dist/index.mjs</code> there, because Tailwind CSS should not purge the css classes of the components library.</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>module<span class="token punctuation">.</span>exports <span class="token operator">=</span> <span class="token punctuation">{</span>
  <span class="token literal-property property">content</span><span class="token operator">:</span> <span class="token punctuation">[</span>
    <span class="token string">"..."</span><span class="token punctuation">,</span>
    <span class="token string">"node_modules/@lawandorga/components/dist/index.mjs"</span><span class="token punctuation">,</span>
  <span class="token punctuation">]</span><span class="token punctuation">,</span>
  <span class="token literal-property property">darkMode</span><span class="token operator">:</span> <span class="token string">"class"</span><span class="token punctuation">,</span>
  <span class="token literal-property property">theme</span><span class="token operator">:</span> <span class="token punctuation">{</span>
    <span class="token literal-property property">extend</span><span class="token operator">:</span> <span class="token punctuation">{</span>
      <span class="token literal-property property">colors</span><span class="token operator">:</span> <span class="token punctuation">{</span>
        <span class="token literal-property property">lorgablue</span><span class="token operator">:</span> <span class="token string">"#003c4d"</span><span class="token punctuation">,</span>
        <span class="token literal-property property">blue</span><span class="token operator">:</span> <span class="token punctuation">{</span>
          <span class="token number">50</span><span class="token operator">:</span> <span class="token string">"#eff9fb"</span><span class="token punctuation">,</span>
          <span class="token number">100</span><span class="token operator">:</span> <span class="token string">"#d0e7ed"</span><span class="token punctuation">,</span>
          <span class="token number">200</span><span class="token operator">:</span> <span class="token string">"#aad0db"</span><span class="token punctuation">,</span>
          <span class="token number">300</span><span class="token operator">:</span> <span class="token string">"#8abbc9"</span><span class="token punctuation">,</span>
          <span class="token number">400</span><span class="token operator">:</span> <span class="token string">"#6ca7b7"</span><span class="token punctuation">,</span>
          <span class="token number">500</span><span class="token operator">:</span> <span class="token string">"#428193"</span><span class="token punctuation">,</span>
          <span class="token number">600</span><span class="token operator">:</span> <span class="token string">"#275f6f"</span><span class="token punctuation">,</span>
          <span class="token number">700</span><span class="token operator">:</span> <span class="token string">"#153f4b"</span><span class="token punctuation">,</span>
          <span class="token number">800</span><span class="token operator">:</span> <span class="token string">"#0a2027"</span><span class="token punctuation">,</span>
          <span class="token number">900</span><span class="token operator">:</span> <span class="token string">"#010203"</span><span class="token punctuation">,</span>
        <span class="token punctuation">}</span><span class="token punctuation">,</span>
      <span class="token punctuation">}</span><span class="token punctuation">,</span>
      <span class="token function-variable function">typography</span><span class="token operator">:</span> <span class="token punctuation">(</span><span class="token parameter"><span class="token literal-property property">theme</span><span class="token operator">:</span> any</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">(</span><span class="token punctuation">{</span>  <span class="token comment">// eslint-disable-line</span>
        <span class="token constant">DEFAULT</span><span class="token operator">:</span> <span class="token punctuation">{</span>
          <span class="token literal-property property">css</span><span class="token operator">:</span> <span class="token punctuation">{</span>
            <span class="token literal-property property">table</span><span class="token operator">:</span> <span class="token punctuation">{</span><span class="token punctuation">}</span><span class="token punctuation">,</span>
            <span class="token literal-property property">thead</span><span class="token operator">:</span> <span class="token punctuation">{</span>
              <span class="token literal-property property">border</span><span class="token operator">:</span> <span class="token string">"none"</span><span class="token punctuation">,</span>
            <span class="token punctuation">}</span><span class="token punctuation">,</span>
            <span class="token literal-property property">tr</span><span class="token operator">:</span> <span class="token punctuation">{</span>
              <span class="token literal-property property">border</span><span class="token operator">:</span> <span class="token string">"none"</span><span class="token punctuation">,</span>
            <span class="token punctuation">}</span><span class="token punctuation">,</span>
            <span class="token string-property property">"tr:last-child"</span><span class="token operator">:</span> <span class="token punctuation">{</span>
              <span class="token literal-property property">borderBottomWidth</span><span class="token operator">:</span> <span class="token string">"0"</span><span class="token punctuation">,</span>
            <span class="token punctuation">}</span><span class="token punctuation">,</span>
            <span class="token literal-property property">th</span><span class="token operator">:</span> <span class="token punctuation">{</span>
              <span class="token literal-property property">verticalAlign</span><span class="token operator">:</span> <span class="token string">"bottom"</span><span class="token punctuation">,</span>
              <span class="token literal-property property">borderWidth</span><span class="token operator">:</span> <span class="token string">"2px"</span><span class="token punctuation">,</span>
              <span class="token literal-property property">borderColor</span><span class="token operator">:</span> <span class="token function">theme</span><span class="token punctuation">(</span><span class="token string">"colors.gray[400]"</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
              <span class="token literal-property property">backgroundColor</span><span class="token operator">:</span> <span class="token function">theme</span><span class="token punctuation">(</span><span class="token string">"colors.gray[200]"</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
              <span class="token literal-property property">padding</span><span class="token operator">:</span> <span class="token string">"4px 8px"</span><span class="token punctuation">,</span>
            <span class="token punctuation">}</span><span class="token punctuation">,</span>
            <span class="token string-property property">"th > p, td > p"</span><span class="token operator">:</span> <span class="token punctuation">{</span>
              <span class="token literal-property property">margin</span><span class="token operator">:</span> <span class="token number">0</span><span class="token punctuation">,</span>
            <span class="token punctuation">}</span><span class="token punctuation">,</span>
            <span class="token literal-property property">td</span><span class="token operator">:</span> <span class="token punctuation">{</span>
              <span class="token literal-property property">verticalAlign</span><span class="token operator">:</span> <span class="token string">"top"</span><span class="token punctuation">,</span>
              <span class="token literal-property property">borderWidth</span><span class="token operator">:</span> <span class="token string">"2px"</span><span class="token punctuation">,</span>
              <span class="token literal-property property">borderColor</span><span class="token operator">:</span> <span class="token function">theme</span><span class="token punctuation">(</span><span class="token string">"colors.gray[300]"</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
              <span class="token literal-property property">backgroundColor</span><span class="token operator">:</span> <span class="token function">theme</span><span class="token punctuation">(</span><span class="token string">"colors.gray[100]"</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
            <span class="token punctuation">}</span><span class="token punctuation">,</span>
            <span class="token string-property property">"tbody td:first-child"</span><span class="token operator">:</span> <span class="token punctuation">{</span>
              <span class="token literal-property property">paddingLeft</span><span class="token operator">:</span> <span class="token string">"auto"</span><span class="token punctuation">,</span>
            <span class="token punctuation">}</span><span class="token punctuation">,</span>
          <span class="token punctuation">}</span><span class="token punctuation">,</span>
        <span class="token punctuation">}</span><span class="token punctuation">,</span>
      <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token punctuation">}</span><span class="token punctuation">,</span>
  <span class="token literal-property property">plugins</span><span class="token operator">:</span> <span class="token punctuation">[</span>
    <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">"@tailwindcss/typography"</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">"@tailwindcss/line-clamp"</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
    <span class="token function">require</span><span class="token punctuation">(</span><span class="token string">"@tailwindcss/aspect-ratio"</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
  <span class="token punctuation">]</span><span class="token punctuation">,</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br><span class="line-number">38</span><br><span class="line-number">39</span><br><span class="line-number">40</span><br><span class="line-number">41</span><br><span class="line-number">42</span><br><span class="line-number">43</span><br><span class="line-number">44</span><br><span class="line-number">45</span><br><span class="line-number">46</span><br><span class="line-number">47</span><br><span class="line-number">48</span><br><span class="line-number">49</span><br><span class="line-number">50</span><br><span class="line-number">51</span><br><span class="line-number">52</span><br><span class="line-number">53</span><br><span class="line-number">54</span><br><span class="line-number">55</span><br><span class="line-number">56</span><br><span class="line-number">57</span><br><span class="line-number">58</span><br><span class="line-number">59</span><br><span class="line-number">60</span><br><span class="line-number">61</span><br><span class="line-number">62</span><br><span class="line-number">63</span><br><span class="line-number">64</span><br><span class="line-number">65</span><br><span class="line-number">66</span><br></div></div><h3 id="shortcut" tabindex="-1"><a class="header-anchor" href="#shortcut" aria-hidden="true">#</a> Shortcut</h3>
<p>You can also use <code>getTailwindConfig</code> and do the following in your <code>tailwind.config.js</code>:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> getTailwindConfig <span class="token keyword">from</span> <span class="token string">"@lawandorga/components"</span><span class="token punctuation">;</span>

content <span class="token operator">=</span> <span class="token punctuation">[</span>
  <span class="token string">"./src/**/*.{vue,js,ts,jsx,tsx}"</span><span class="token punctuation">,</span>
<span class="token punctuation">]</span>

module<span class="token punctuation">.</span>exports <span class="token operator">=</span> <span class="token function">getTailwindConfig</span><span class="token punctuation">(</span>content<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><h2 id="use" tabindex="-1"><a class="header-anchor" href="#use" aria-hidden="true">#</a> Use</h2>
<div class="language-vue ext-vue line-numbers-mode"><pre v-pre class="language-vue"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>script</span> <span class="token attr-name">setup</span> <span class="token attr-name">lang</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>ts<span class="token punctuation">"</span></span><span class="token punctuation">></span></span><span class="token script"><span class="token language-javascript">
    <span class="token keyword">import</span> ButtonNormal <span class="token keyword">from</span> <span class="token string">"@lawandorga/components"</span><span class="token punctuation">;</span>
</span></span><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>script</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div></template>
